// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Brand");

                    b.Property<int>("Cost")
                        .HasColumnType("int")
                        .HasColumnName("Cost");

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Discription");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Leatherman",
                            Cost = 2640,
                            Discription = "1. Тонкі пасатижі\r\n2. Звичайні пасатижі\r\n3. Кусачки для твердого дроту\r\n4. Кусачки для дроту\r\n5. Інструмент для зачищення дротів\r\n6. Клинок зі сталі 420НС\r\n7. Різак для відкривання упаковок\r\n8. Лінійка (1.5 дюйма/3.8 см)\r\n9. Відкривачка консервних банок\r\n10. Відкривачка пляшок\r\n11. Напилок для дерева/металу\r\n12. Викрутка Філліпс\r\n13. Середня викрутка\r\n14. Мала викрутка",
                            Image = "https://content.rozetka.com.ua/goods/images/big/57818359.jpg",
                            Name = "Мультитул Leatherman Rev Silver"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Leatherman",
                            Cost = 5760,
                            Discription = "• Гострогубці\r\n • Плоскогубці\r\n • Змінні кусачки для дротів\r\n • Змінні кусачки для товстих дротів\r\n • Ніж зі сталі 420HC\r\n • Серейторний ніж зі сталі 420HC\r\n • Пила\r\n • Ножиці\r\n • Напилок для дерева/металу\r\n • Алмазний напилок\r\n • Великий Bit Driver\r\n • Маленький Bit Driver\r\n • Середньорозмірна викрутка\r\n • Лінійка (8 inch/19 cm)\r\n • Відкривачка для пляшок\r\n • Відкривачка для банок\r\n • Інструмент для зачищення дротів",
                            Image = "https://content1.rozetka.com.ua/goods/images/big/179619842.jpg",
                            Name = "Мультиінструмент Leatherman WAVE PLUS"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Leatherman",
                            Cost = 8920,
                            Discription = "Гострогубці\r\nПлоскогубці\r\nЗнімні кусачки зі сталі 154CM\r\nЗмінні посилені кусачки зі сталі 154CM\r\nОбтиск для електричних роз'ємів\r\nКомбіноване лезо зі сталі 420HC\r\nПила\r\nУдарний молоточок\r\nЗмінний гак-різак\r\nІнструмент для витягання зам'ятих гільз\r\nЗмінний інструмент для розбирання вогнепальної зброї\r\nЗмінний бронзовий скребок\r\nОчисний стрижень/Адаптер для щітки\r\nКарабін / Відкривачка для пляшок\r\nВеликий Bit Driver\r\n1/2\" гайковий ключ\r\n3/8\" гайковий ключ",
                            Image = "https://content.rozetka.com.ua/goods/images/big/10981351.jpg",
                            Name = "Мультитул Leatherman Mut"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Leatherman",
                            Cost = 7200,
                            Discription = "Гострогубці\r\nПлоскогубці\r\nЗнімні кусачки зі сталі 154 см\r\nЗнімні кусачки для товстого дроту зі сталі 154 см\r\nІнструмент для зачищення дротів\r\nНіж з серейтором зі сталі 420НС\r\nПила\r\nМолоток\r\nШило з отвором\r\nВідкривачка для банок\r\nВідкривачка для пляшок\r\nТримач для шестигранних біт ¼ дюйма\r\nТримач для великих біт\r\nНакидний гайковий ключ ¼ дюйма\r\nКарабін/відкривачка для пляшок\r\nНакидний гайковий ключ 3/16 дюйма\r\nСвисток\r\nКресало\r\nАлмазна стругачка",
                            Image = "https://content2.rozetka.com.ua/goods/images/big/16891149.jpg",
                            Name = "Мультиінструмент Leatherman Signal"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Leatherman",
                            Cost = 4800,
                            Discription = "Інструменти в комплекті - Медичні ножиці з нержавіючої сталі 420 НС\r\nСтропоріз\r\nСклобій\r\nКільцеріз\r\nЧохол-кріплення з міцного полімеру\r\nЛінійка (5 см)\r\n\r\nВага - 168 г\r\nДовжина - 12.7 см\r\nЧохол у комплекті - Є\r\nТип - Повнорозмірні\r\nКількість інструментів - 6\r\nКраїна реєстрації бренду - США\r\nГарантія - 12 місяців\r\nКраїна-виробник товару - США",
                            Image = "https://content2.rozetka.com.ua/goods/images/big/10980378.jpg",
                            Name = "Мультитул Leatherman Raptor"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Leatherman",
                            Cost = 3960,
                            Discription = "Інструменти в комплекті\r\n- Комбінований ніж зі сталі 420НС;\r\n- Гострогубці;\r\n- Плоскогубці;\r\n- Захват для гайок і циліндрів;\r\n- Кусачки;\r\n- Кусачки для твердого дроту;\r\n- Бітотримач для великих біт;\r\n- Відкривачка для пляшок;\r\n- Карабін;\r\n- Змінні біти.\r\n\r\nВага - 142 г\r\nДовжина - 10 см\r\nЧохол у комплекті - Без чохла\r\nЗастосування - Для рибалки\r\nТип - Повнорозмірні\r\nКількість інструментів - 7\r\nГарантія - 5 років\r\nКраїна-виробник товару - США",
                            Image = "https://content1.rozetka.com.ua/goods/images/big/45289318.jpg",
                            Name = "Мультитул Leatherman Skeletool"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
